# Warning, all string entries are CASE SENSITIVE. Please ensure you put EXACTLY the right case in from the listed options.

[DEFAULT] # Used for loading and making the default configuration, and for reference when modifying config files (explains what things do)
    use_vanilla_signals = true 
    # Use included vanilla signals for both Space Age and Factorio. Disable to use entirely custom signals.
    use_custom_signals = false
    # Use custom signals, including modded signals.
    use_custom_quality = false
    # Use modded qualites to "reuse" signals 
    use_space_age = false 
    # Use Space Age DLC when generating signals
    use_quality = false 
    # Use Quality when generating signals
    bypass_custom_signal_warning = False 
    # Bypass the warning about using custom signals.
    bypass_custom_and_vanilla_signal_warning = False 
    # Bypass the warning disabling vanilla signals when using custom ones, and allows you to use both custom signals and the included signals.
    custom_signal_json_path = Custom Signals\custom_signals_example.json
    # Use a decoded base64 json file of a constant combinator of all the signals you want. This uses the textplates mod as an example.
    custom_quality_json_path  = Custom Signals\custom_quality_example.json
    # Json file containing all the modded qualities used. (Follow the same format as the example.)
    colour_mode = 256 bit 
    # 2 bit, 256 bit, full colour (2 bit is black and white, 256 bit is 256 colour, full colour is full colour depth. Recommended is 256 bit)
    video_width = 32 
    # Target video width, width of lamps inside Factorio
    video_height = 18
    # Target video height, height of lamps inside Factorio
    use_data_cache =  true 
    # Stores any data that was computed, and uses it again if possible if no settings have changed. Increases generation speed.
    substation_range = 8 
    # Tells the program how many combinators it can place before it requires a space for a substation. Leave at 13 for legendary substations, or use 8 for normal quality
    use_chunking = true
    # Should the program divide the rendering process into multiple blueprints?
    chunk_size = 100
    # Tells the program how many frames it should generate before pausing to allow you to paste blueprints. Usefull when you are processing large videos when generating memory cells.
    combinator_width = 100 
    # How wide in terms of combinators should the memory cells be?
    saturation = 1
    # How Saturated the output video will be on the lamps. Try increasing this if colours look drowned out in game. Default 1. (ffmpeg filter)
    brightness = 0
    # How Bright the output video will be on the lamps. (Colour Correction, ffmpeg filter)
    contrast = 1
    # Video Contrast (ffmpeg filter)
    gamma = 1
    # Video Gamma Filter, Overall Brightness. (Increase this instead of brightness if the video is too dark)

[VIDEO_PLAYER]
    use_default_settings = false
    # Disable to use this config section, otherwise the program will always use default settings.
    use_vanilla_signals = false
    use_custom_signals = true
    use_custom_quality = true
    use_space_age = true
    use_quality = true
    bypass_custom_signal_warning = true
    bypass_custom_and_vanilla_signal_warning = true
    custom_signal_json_path = Custom Signals\space_age_2.07.json
    custom_quality_json_path  = Custom Signals\custom_quality_example.json
    colour_mode = full colour
    video_width = 220
    video_height = 124
    use_data_cache =  true
    substation_range = 13
    use_chunking = false
    chunk_size = 300
    combinator_width = 100
    # DO NOT MESS WITH THE FOLLOWING UNLESS YOU KNOW WHAT YOU ARE DOING!
    saturation = 1
    #  NOTE, colours will probbably be drowned out since Factorio lamps suck, you will probbably want to increase this.
    brightness = 0
    contrast = 2.92
    gamma = 0
[DEBUG]
    # NOTE: The following options are debug options. Ive left them in so you can play around with them, but most people should not touch this.

    set_specific_frame = false
    # Should the program only render one specific frame?
    specific_frame = 1800
    # If so, what frame should the program render?
    use_artifical_video_length = true
    # Should the program stop rendering after a set amount of frames (time)?
    frame_limit = 100
    # If so, what frame should the program finish rendering at?
    start_frame = 1500
    # What frame should the program start on?
    use_debug_frame_count = false
    # Instead of treating each frame like its represented in the source video, instead always start frame count from 0. I.e: Frame 500 becomes frame 0 if you start at Frame 500


