[DEFAULT] # Used for loading and making the default configuration, and for reference when modifying config files (explains what things do)
    use_vanilla_signals = true 
    # Use included vanilla signals for both Space Age and Factorio. Disable to use entirely custom signals.
    use_custom_signals = false
    # Use custom signals, including modded signals.
    use_custom_quality = false
    # Use modded qualites to "reuse" signals 
    use_space_age = false 
    # Use Space Age DLC when generating signals
    use_quality = false 
    # Use Quality when generating signals
    bypass_custom_signal_warning = False 
    # Bypass the warning about using custom signals.
    bypass_custom_and_vanilla_signal_warning = False 
    # Bypass the warning disabling vanilla signals when using custom ones, and allows you to use both custom signals and the included signals.
    custom_signal_json_path = Custom Signals\custom_signals_example.json
    # Use a decoded base64 json file of a constant combinator of all the signals you want. This uses the textplates mod as an example.
    custom_quality_json_path  = Custom Signals\custom_quality_example.json
    # Json file containing all the modded qualities used. (Follow the same format as the example.)
    colour_mode = 256 bit 
    # 2 bit, 256 bit (2 bit is black and white, recommended 256 bit)
    video_width = 64 
    # Target video width, width of lamps inside Factorio
    video_height = 36
    # Target video height, height of lamps inside Factorio
    use_data_cache =  true 
    # Stores any data that was computed, and uses it again if possible if no settings have changed. Increases generation speed.
    substation_range = 8 
    # Tells the program how many combinators it can place before it requires a space for a substation. Leave at 13 for legendary substations, or use 8 for normal quality
    chunk_size = 100
    # Tells the program how many frames it should generate before pausing to allow you to paste blueprints. Usefull when you are processing large videos when generating memory cells.
    combinator_width = 100 
    # How wide in terms of combinators should the memory cells be?
    use_artifical_video_length = false
    # Should the program use a frame limit or not?
    frame_limit = 100
    # Amount of frames that the program will render if use_artifical_video_length = true

[VIDEO_PLAYER]
    use_default_settings = false 
    # Disable to use this config section, otherwise the program will always use default settings.
    use_vanilla_signals = true
    use_custom_signals = false
    use_custom_quality = true
    use_space_age = true
    use_quality = true
    bypass_custom_signal_warning = true
    bypass_custom_and_vanilla_signal_warning = true
    custom_signal_json_path = Custom Signals\custom_example.json
    custom_quality_json_path  = Custom Signals\custom_quality_example.json
    colour_mode = 256 bit
    video_width = 109
    video_height = 191
    use_data_cache =  true
    substation_range = 13
    chunk_size = 10000
    combinator_width = 100
    use_artifical_video_length = false
    frame_limit = 100

